apiVersion: v1
kind: Service
metadata:
  name: webnotes-mongo
  labels:
    app: webnotes
spec:
  ports:
    - port: 27017
  selector:
    app: webnotes
    tier: mongo
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pv-claim
  labels:
    app: webnotes
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webnotes-mongo
  labels:
    app: webnotes
spec:
  selector:
    matchLabels:
      app: webnotes
      tier: mongo
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: webnotes
        tier: mongo
    spec:
      containers:
      - image: mongo
        name: mongo
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom: 
            secretKeyRef:
              name: webnotes-secret
              key: MONGODB_USERNAME
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: webnotes-secret
              key: MONGODB_PASSWORD
        ports:
          - containerPort: 27017
            name: mongo
        volumeMounts:
        - name: mongo-persistent-storage
          mountPath: /data/db
      volumes:
      - name: mongo-persistent-storage
        persistentVolumeClaim:
          claimName: mongo-pv-claim
