---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webnotes-mongo-pv-claim
  labels:
    name: webnotes-mongo-pvc
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "{{ .Values.pvClaimStorage }}"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webnotes-mongo
  labels:
    name: webnotes-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      name: webnotes-mongo
  strategy:
    type: "Recreate"
  template:
    metadata:
      labels:
        name: webnotes-mongo
    spec:
      containers:
      - image: "mongo"
        name: "mongo"
        env:
          - name: MONGO_INITDB_DATABASE
            value: app
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom: 
              secretKeyRef:
                name: {{ .Values.secretName }}
                key: MONGODB_USERNAME
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secretName }}
                key: MONGODB_PASSWORD
        ports:
          - containerPort: 27017
            name: "mongo-port"
        volumeMounts:
        - name: "mongo-persistent-storage"
          mountPath: "/data/db"
      volumes:
      - name: "mongo-persistent-storage"
        persistentVolumeClaim:
          claimName: "webnotes-mongo-pv-claim"


