apiVersion: v1
kind: Service
metadata:
  name: {{ include "webnotes.fullname" . }}
  labels:
    {{- include "webnotes.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "webnotes.selectorLabels" . | nindent 4 }}

---
apiVersion: v1
kind: Service
metadata:
  name: webnotes-mongo
  labels:
    name: webnotes-mongo  
spec:
  type: ClusterIP
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
      name: mongo
  selector:
    name: webnotes-mongo  
