---
AWSTemplateFormatVersion: '2010-09-09'
Description: This template deploys mondoDB to ecs cluster.

Parameters:
  Environment:
    Type: String
    Default: dev
    Description: Environment for the project. By default it's dev.
    AllowedValues:
      - dev
      - prod

  ProjectName:
    Type: String
    Default: notes
    Description: Name of the project.

  DatabaseDockerImage:
    Description: The Docker image to pull database from Docker Hub
    Type: String
    Default: "public.ecr.aws/docker/library/mongo:latest"

  DesiredCount:
    Description: How many instances of this task should we run across our cluster?
    Type: Number
    Default: 1

  DBPort:
    Type: Number
    Default: 27017
    Description: Database port. By default mongo db port is 27017.

  DBUsername:
    Type: String
    Description: MongoDB user name.

  DBPassword:
    Type: String
    Description: MongoDB user password.

  Subnet:
    Type: AWS::EC2::Subnet::Id
    Description: Subnet where to deploy database service.

Resources:
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Ref Environment
      CapacityProviders:
        - FARGATE
        - FARGATE_SPOT

  DatabaseTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      TaskRoleArn: !Ref TaskRole
      ExecutionRoleArn: !Ref ServiceRole
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      RuntimePlatform:
        OperatingSystemFamily: LINUX
      Cpu: 256
      Memory: 512
      ContainerDefinitions:
        - Name: mongodb-service
          Essential: true
          Image: !Ref DatabaseDockerImage
          Environment:
            - Name: "region"
              Value: !Ref AWS::Region
            - Name: MONGO_INITDB_ROOT_USERNAME
              Value: !Ref DBUsername
            - Name: MONGO_INITDB_ROOT_PASSWORD
              Value: !Ref DBPassword
          PortMappings:
            - ContainerPort: !Ref DBPort
              Protocol: tcp
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref AWS::StackName
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: !Ref Environment

  DatabaseService:
    Type: AWS::ECS::Service
    DependsOn: ECSCluster
    Properties:
      ServiceName: db-service
      Cluster: !Ref ECSCluster
      DesiredCount: !Ref DesiredCount
      TaskDefinition: !Ref DatabaseTaskDefinition
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets:
            - !Ref Subnet

  CloudWatchLogsGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Ref AWS::StackName
      RetentionInDays: 1

  TaskRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ecs-task-${AWS::StackName}
      Path: /
      AssumeRolePolicyDocument: |
        {
            "Statement": [{
                "Sid": "",
                "Effect": "Allow",
                "Principal": { "Service": [ "ecs-tasks.amazonaws.com" ]},
                "Action": "sts:AssumeRole"
            }]
        }

  ServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ecs-service-${AWS::StackName}
      Path: /
      AssumeRolePolicyDocument: |
        {
            "Statement": [{
                "Effect": "Allow",
                "Principal": { "Service": [ "ecs-tasks.amazonaws.com" ]},
                "Action": [ "sts:AssumeRole" ]
            }]
        }
      Policies:
        - PolicyName: !Sub ecs-service-${AWS::StackName}
          PolicyDocument:
            {
              "Version": "2012-10-17",
              "Statement": [ {
                "Effect": "Allow",
                "Action": [
                  "ecr:GetAuthorizationToken",
                  "ecr:BatchCheckLayerAvailability",
                  "ecr:GetDownloadUrlForLayer",
                  "ecr:BatchGetImage",
                  "logs:CreateLogStream",
                  "logs:PutLogEvents"
                ],
                "Resource": "*"
              } ]
            }

Outputs:
  Cluster:
    Description: A reference to the ECS cluster
    Value: !Ref ECSCluster

  Database:
    Description: A reference to the Database service
    Value: !Ref DatabaseService